Don't update statistics if generation fails

diff --git a/cookbooks/web/templates/default/statistics.erb b/cookbooks/web/templates/default/statistics.erb
--- a/cookbooks/web/templates/default/statistics.erb
+++ b/cookbooks/web/templates/default/statistics.erb
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# Abort on error
+set -e
+
 # Make sure /usr/local/bin is on the path
 export PATH=$PATH:/usr/local/bin
 
